### ISSUE TITLE
Fork license

### ISSUE THREAD

**Issue by WouterSioen** [friends-of-forkcms/fork-cms-module-compression#1]
Great work, it looks like a great module. I'll add some (minor) issues though.

You use the Fork licence part, stating that your files are part of Fork CMS. That's not true and should not be included in your module. (I know that this is done wrong in a lot of modules, but thats no reason to do it wrong in yours :wink: )

```
/*
 * This file is part of Fork CMS.
 *
 * For the full copyright and license information, please view the license
 * file that was distributed with this source code.
 */
```

**Comment by jessedobbelaere** [comment]
You're right, i'll fix that asap :-) I usually copy the basic structure from the default modules and forget to remove the license.

**Comment by WouterSioen** [comment]
We're also planning on removing this from Fork itself, since the LICENCE file in the doc root is enough.
