### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by VegasRideshareKing** [friends-of-forkcms/fork-cms-module-compression#13]
I was installing some themes from here and i got this message on the last 2:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by jessedobbelaere** [comment]
Hi @VegasRideshareKing, this is a module (not a theme). Which theme are you trying? Can you create an issue there? Note that some themes are not compatible with the latest Fork CMS versions. You can enable debug mode by setting environment variable `FORK_DEBUG=1` or manually setting `$debug = true;` in line https://github.com/forkcms/forkcms/blob/master/index.php#L25
