### ISSUE TITLE
Compress images only once

### ISSUE THREAD

**Issue by WouterSioen** [friends-of-forkcms/fork-cms-module-compression#2]
I didn't see a mechanism to avoid compressing images multiple times. If you have a really big amount of images, this could cause performance problems. I would only compress the image if it isn't available in the compress_history table.

**Comment by jessedobbelaere** [comment]
That's right, but how can you notice that a file is edited or reuploaded in a module and should be compressed again? Maybe check the shrinked file size in the database too and compress it if the filesize doesnt match/larger.   

Fortunately, the tinyPNG api doesn't use one of your 500 tokens if you try to compress an image that can't be improved. But i noticed that if you recompress a file, it usually shrinks another 1% and the third time it can't be improved anymore. 

So yes, i agree this should be implemented for performance reasons.

**Comment by WouterSioen** [comment]
You could use checksum verification to check if a file is changed? If you save a hash (md5/sha) of the files content after compressing the file, you can check if it's changed on disk. Checksum verification is a more common practice then verifying file size.

**Comment by jessedobbelaere** [comment]
The module now checks if there's a record in the history table with the same path, and if it exists then the SHA1 hash is compared. Seems to work great.

I also cleaned up a lot of code and made a separate API class with better error handeling (like when you try to compress but the API key is invalid.) Note that the API only has 1 call method (compressing an image), so I can't implement an API key check when you first enter the key, but you'll get the warning when you compress some images).

The cronjob and Ajax files seem to be having [almost exactly the same code](https://github.com/jessedobbelaere/fork-cms-module-compression/blob/master/src/Backend/Modules/Compression/Cronjobs/CompressImages.php#L45-L81). I'll better move that code to avoid duplicate code. Should I put it in Model..? I'm not sure.
